

protos:
	protoc --go_out=module=github.com/mfield4/go_entity_component_services/protos:. components.proto
	protoc --go_out=module=github.com/mfield4/go_entity_component_services/protos:. protoecs.proto
	protoc --go_out=module=github.com/mfield4/go_entity_component_services/protos:. commands.proto
